# Network Topology Documentation

## Overview
This document describes the network topology and configuration for the infrastructure.

## VPC Configuration
- **VPC CIDR Block**: `${vpc_cidr_block}`
- **NAT Gateway**: ${enable_nat_gateway ? "Enabled" : "Disabled"}
- **Single NAT Gateway**: ${single_nat_gateway ? "Yes" : "No"}

## Subnets

### Public Subnets
%{ for name, config in public_subnets ~}
- **${name}**
  - CIDR: `${config.cidr_block}`
  - Availability Zone: `${config.availability_zone}`
  - Type: `${config.type}`
%{ endfor ~}

### Private Subnets
%{ for name, config in private_subnets ~}
- **${name}**
  - CIDR: `${config.cidr_block}`
  - Availability Zone: `${config.availability_zone}`
  - Type: `${config.type}`
%{ endfor ~}

### Database Subnets
%{ for name, config in database_subnets ~}
- **${name}**
  - CIDR: `${config.cidr_block}`
  - Availability Zone: `${config.availability_zone}`
  - Type: `${config.type}`
%{ endfor ~}

## Security Groups
%{ for sg_name, sg_config in security_groups ~}
### ${sg_name}
- **Description**: ${sg_config.description}

#### Ingress Rules
%{ for rule in sg_config.ingress_rules ~}
- Port ${rule.from_port}${rule.from_port != rule.to_port ? "-${rule.to_port}" : ""} (${rule.protocol}) from ${join(", ", rule.cidr_blocks)}
%{ endfor ~}

#### Egress Rules
%{ for rule in sg_config.egress_rules ~}
- Port ${rule.from_port}${rule.from_port != rule.to_port ? "-${rule.to_port}" : ""} (${rule.protocol}) to ${join(", ", rule.cidr_blocks)}
%{ endfor ~}
%{ endfor ~}

## Network ACLs
%{ for nacl_name, nacl_config in network_acls ~}
### ${nacl_name}
- **Associated Subnets**: ${join(", ", nacl_config.subnet_names)}

#### Ingress Rules
%{ for rule in nacl_config.ingress_rules ~}
- Rule ${rule.rule_number}: ${rule.rule_action} ${rule.protocol} ${rule.from_port}-${rule.to_port} from ${rule.cidr_block}
%{ endfor ~}

#### Egress Rules
%{ for rule in nacl_config.egress_rules ~}
- Rule ${rule.rule_number}: ${rule.rule_action} ${rule.protocol} ${rule.from_port}-${rule.to_port} to ${rule.cidr_block}
%{ endfor ~}
%{ endfor ~}

%{ if enable_nat_gateway ~}
## NAT Gateways
%{ for nat_name, nat_config in nat_gateways ~}
- **${nat_name}**: Associated with subnet `${nat_config.subnet_name}`
%{ endfor ~}
%{ endif ~}

## Common Tags
%{ for key, value in common_tags ~}
- **${key}**: ${value}
%{ endfor ~}

---
*Generated by Terraform on ${timestamp()}*